#!/usr/bin/env php
<?php
/**
 * @author Benjamin Grandfond <benjamin.grandfond@gmail.com>
 * @since 23/10/11
 */
set_time_limit(0);

require_once __DIR__.'/autoload.php';

use Silexor\Application;

$app = new Application();
$app->run();